sonar.projectKey=cbx6664-rag
sonar.organization=cbx6664

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=RAG Microservices
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.exclusions=**/*_test.py,**/node_modules/**,**/.venv/**,**/tests/**,**/.next/**,**/coverage/**

# Python specific settings
sonar.python.coverage.reportPaths=ingestion-service/coverage.xml,inference-service/backend/coverage.xml
sonar.python.xunit.reportPath=ingestion-service/test-reports/*.xml,inference-service/backend/test-reports/*.xml

# JavaScript/TypeScript specific settings
sonar.typescript.lcov.reportPaths=inference-service/frontend/coverage/lcov.info
sonar.javascript.lcov.reportPaths=inference-service/frontend/coverage/lcov.info

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
